Betterment/test_track

.gitignore, README.md, db/seeds.rb, lib/tasks/seed_app.rake
/domain @samandmoore @rynonl @nonrational @joejansen
This PR introduces a `db/seeds.rb` file that loads a `.gitignore`d YAML file that is expected to contain a serialized hash of app-name/auth_secret pairs to allow injection of local dev app seeds via laptop config management (e.g. boxen).
It also includes a rake task `rake seed_app[`*app_name*`]` that will idempotently create/update the YAML file and append/regenerate an app seed with a random password to the `app_seeds.yml`, and load it into the current environment's database (usually `development`).
The console output of running `rake seed_app[foo_app]` looks something like this:
```
Ensured foo_app app
foo_app configured in db/seed_apps.yml and loaded into your database.
Set the following environment variable in your app (e.g. via …
```
=> Add seed_app support

app/controllers/admin/decisions_controller.rb, app/models/decision.rb, app/views/api/assignment_registries/show.json.jbuilder, app/views/api/identifier_visitors/show.json.jbuilder, app/views/api/identifiers/create.json.jbuilder, app/views/api/split_registries/show.json.jbuilder, app/views/api/v1/visitors/_show.json.jbuilder, app/views/api/visitors/_show.json.jbuilder, app/views/api/visitors/show.json.jbuilder
There are a couple other things in here - there are dead templates related to long dead routes I removed because I saw them. Also, a test was relying on created_at return sequence of assignments in the visitor. The performance tradeoff should be tiny to make those deterministic, even without an index on created_at, because a visitor has a very small number of assignments to return.
=> Batch decisions

config/puma.rb
/domain @jmileham 
since we've got a Procfile now and we're endorsing foreman-backed deployment processes that include their own process supervisor, we don't need nor want to daemonize our puma process nor track its PID.
=> rely on external supervisor for puma

app/controllers/admin/decisions_controller.rb, app/jobs/create_decision_job.rb, app/models/decision.rb, config/application.rb, spec/features/admin_split_decision_create_spec.rb
this operation can take a long time to execute on a split that has lots
of assignments to reassign. this change pushes the execution of
reassignment into a background job. this change also trades off
guarantees that we only create a single BulkAssignment for the Decision.
in the non-optimal case, the job will die while executing the
reassignments in batches. when that happens, the job will re-run and
pick up the reassignment process where it left off with the one
unfortunate side effect of creating another BulkAssignment.
/domain @jmileham @rynonl 
Note: this PR also introduces ActiveJob over using `split.delay.create_decision!(...)`. I may have gotten the joint wrong, but it feels okay.
=> move the split decision execution into an activejob

app/assets/javascripts/application.js, app/inputs/collection_radio_buttons_input.rb, app/inputs/collection_select_input.rb, app/inputs/grouped_collection_select_input.rb, app/inputs/percent_input.rb, app/inputs/radio_button.rb, app/inputs/radio_button_input.rb, app/inputs/string_input.rb, config/initializers/date_time_formats.rb, vendor/gems/style-closet/app/assets/javascripts/style-closet/base_inputs.js, vendor/gems/style-closet/app/assets/javascripts/style-closet/dropdowns.js, vendor/gems/style-closet/app/assets/javascripts/style-closet/flashes.js, vendor/gems/style-closet/app/assets/javascripts/style-closet/radio_buttons.js, vendor/gems/style-closet/app/assets/javascripts/style_closet.js
Summary of Changes
* new javascript files and their related form helpers to support new designs. waiting for the next PR to implement these forms with full deprecation of bootstrap
* added datetime helpers to support new designs
* added layout helper methods to support new layout styles (to be implemented in the next PR)
TBD
* need to determine if the `vendor_deps` rake task should be updated to support importing javascript files (or perhaps _only_ the javascript files we need) 
=> Form support for new designs

config/puma.rb
The Heroku button regressed because our puma.conf (which used to be ignored but seems to be used by Heroku now) is not aligned with a Heroku 12-factor app - it uses unconventional thread/worker variable names and binds to a unix socket instead of a TCP port. I made switching to TCP conditional on the presence of a PORT env var, which Heroku provides, and added fall-thru to the heroku conventional thread scaling variable names. In the process I swapped the ordering of the preload to be more conventional with Heroku's recommended config. I'm not sure whether this will cause trouble for our production setup at Betterment. We'll want to do a stage deploy after merge and possibly a follow-on patch if it doesn't deploy correctly in our env anymore.
Thanks @thestumonkey for reporting #38
/domain …
=> Fix Heroku button

.editorconfig, app/controllers/admin/splits_controller.rb, app/controllers/admin/variant_details_controller.rb, app/models/split.rb, app/models/variant_detail.rb, app/presenters/split_presenter.rb, app/presenters/variant_presenter.rb, app/views/admin/splits/_variants.html.erb, app/views/admin/variant_details/edit.html.erb, app/views/layouts/application.html.erb, app/views/shared/_header.html.erb, config/routes.rb, db/migrate/20170316204717_create_variant_details.rb, db/schema.rb, spec/factories/variant_details.rb, spec/features/admin_split_config_create_spec.rb, spec/features/admin_variant_details_edit_spec.rb, spec/models/split_spec.rb, spec/models/variant_detail_spec.rb, spec/models/variant_presenter_spec.rb, spec/support/pages/admin/split_show_page.rb, spec/support/pages/admin/variant_details_edit_page.rb
Adding the data model and initial form for adding human-readable metadata to variants. I'd like to wait for @agirlnamedsophia to land her style changes before this gets merged, but I think it's ready to look at.
/domain @Betterment/test_track_core @agirlnamedsophia
=> Add table and edit form for variant metadata

app/assets/stylesheets/components/_tables.scss, app/controllers/admin/split_details_controller.rb, app/models/split_detail.rb, app/views/admin/splits/_test_overview.html.erb, app/views/admin/splits/_variants.html.erb, app/views/api/v1/split_details/_variant_detail.json.jbuilder, app/views/api/v1/split_details/show.json.jbuilder, spec/features/admin_split_config_create_spec.rb, spec/features/admin_variant_details_edit_spec.rb, spec/features/admin_variant_retirement_create_spec.rb, spec/requests/api/v1/split_details_spec.rb, spec/support/pages/admin/split_show_page.rb
* adds variant details to split_details endpoint
* modifies split show page view to display new variant detail information and adds respective feature tests 
/domain @Betterment/test_track_core @dschaub
=> Adds variant details to split_details endpoint

app/models/split_detail.rb, spec/requests/api/v1/split_details_spec.rb
This fixes a bug where we were exposing an empty array of variant details that had not been updated with new display names and descriptions, and uses the `SplitPresenter` class to set the `variant_details` on the `SplitDetail` model. 
/domain @Betterment/test_track_core @dschaub
=> Properly includes variant details by way of the split presenter

app/views/admin/split_details/edit.html.erb, app/views/admin/splits/_test_overview.html.erb
This cleans up some domain specific language we had in the view. This also adjusts the split details edit page with some increased margin to make that view consistent with the others. And this removes a duplicate field on the footer in one view.
/domain @Betterment/test_track_core @dschaub
=> Small cleanups

app/views/admin/splits/_details.html.erb, app/views/admin/splits/_test_overview.html.erb, app/views/admin/splits/_variants.html.erb, app/views/admin/variant_details/edit.html.erb, spec/features/admin_split_details_create_spec.rb, spec/features/admin_variant_details_edit_spec.rb, spec/features/admin_variant_retirement_create_spec.rb, spec/support/pages/admin/split_show_page.rb, spec/support/pages/admin/variant_details_edit_page.rb
* Moves "Decide split" link to a button in the "Split Details" module on the split page
* Modifies language on split show page to emphasize SPLIT over TEST
* Updates tests
/domain @Betterment/test_track_core @jmileham @samandmoore
=> Increases visibility around retiring variants and deciding splits

Gemfile, Gemfile.lock, spec/rails_helper.rb
In my haste to get all the upgrades working, I included the bare `factory_bot` gem which required more config than `factory_bot_rails` does. So I fixed it.
/domain @aburgel 
/no-platform
=> Less config needed when you use the rails gem

Gemfile, Gemfile.lock, config/environments/demo.rb, config/environments/labs.rb, config/environments/production.rb, config/environments/stage.rb
I think the Rails 5 stuff broke some logging. This is an attempt to fix that, but we should confirm in stage that this is the correct solution.
Also this resolves #18 - we don't need the gem dependency.
/platform @jmileham @aburgel @samandmoore
=> Ditch logentries gem, explicitly log to STDOUT in prod/stage

Gemfile, Gemfile.lock, config/application.rb
/no-platform
/cc @smudge 
The [rails_semantic_logger](https://github.com/rocketjob/rails_semantic_logger) gem allows you to format log messages using json (among other things), which is much easier to parse. This PR provides an option to use the gem via an environment variable.
=> Add semantic logger with json output

config/puma.rb
/domain @Betterment/test_track_core @agirlnamedsophia 
/no-platform
Forgot that we need to add a bit of config for Semantic Logger to work with Puma: https://rocketjob.github.io/semantic_logger/forking.html#puma
The `if defined?` conditional ensures that we don't depend on the library if its not enabled.
=> Fix semantic logger with puma

app/models/visitor_supersession.rb
we occasionally see two supersessions occur concurrently for the same
visitor. one of those will succeed and the other will fail. this results
in the loss of the supersession history. this is not really a huge deal,
but the annoying thing is that this results in an inactionable error.
the solution in this changeset is to use savepoints and rescuing to
swallow the unique violations.
/platform @jmileham @aburgel 
Does anyone know if i definitely do or do not have to capture the `PG::UniqueViolation`? I believe that Rails will wrap that in `ActiveRecord::RecordNotUnique`, but it's hard to reproduce this exact case locally.
=> address race condition in visitor supersession

config/initializers/rack_timeout.rb
It's generally a good thing to set tighter timeouts on your endpoints. This changes the timeout from 2 minutes to 30 seconds. We occasionally see 30ish second requests loading splits with large #s of assignments the first time. All that time is spent in PG. Until we come up with a solution to that, we're going to cap our timeout at 30 seconds. We used to need it to be even longer because we had a bunch of admin features that didn't run in the background, but all but one of those (variant retirement) is backgrounded now. Since we don't use that feature very often, we're prioritizing this change over backgrounding that feature.
We're also changing it so that logging for rack-timeout only occurs in production environments and only at the ERROR log level. rack-timeout logs too much otherwise. …
=> don't log rack-timeout things except errors, cut down max service time

config/application.rb, config/environments/demo.rb, config/environments/development.rb, config/environments/labs.rb, config/environments/production.rb, config/environments/stage.rb
1. Propogate conditional usage of taggedLogger based on semantic logger env var. This didn't cause actual symptoms because it was overwritten later, but I think this clarifies the intent.
2. Use the app name to avoid the current default of 'Semantic Logger'
/domain @Betterment/test_track_core @samandmoore
=> Semantic Logger improvements

README.md, app/models/deterministic_assignment_creation.rb, app/models/split_creation.rb, app/views/admin/split_configs/new.html.erb, app/views/admin/splits/_details.html.erb, app/views/admin/splits/_variants.html.erb, app/views/admin/variant_details/edit.html.erb, db/migrate/20180412153251_add_split_feature_gate.rb, db/schema.rb, spec/models/deterministic_assignment_creation_spec.rb, spec/models/split_creation_spec.rb
Because feature gates are not used for analysis, there's no need to record anything but overrides for feature gates. This will vastly reduce the data that needs to change when deciding a feature gate split. It also will cause reweighting feature gates to affect clients in the field instantly unless they've been overridden.
Also explain the difference between experiments and gates to admins.
This is compatible with all clients currently in the field, though behavior will change a bit. The chrome extension will reflect that no matter how many times you've experienced a gate, you are not assigned to a variant unless you assigned it via the extension or admin interface (or before this upgrade took place).
This should make slow rolling features much easier.
This is currently heuristically …
=> Don't record assignment events for feature gates

app/models/split.rb
The current name validations output somewhat ambiguous and vague error messages. In my opinion, it is not clear what the error message refers to as it reads as though the name is being interpreted as 'new'. It was only until I dove into the code did I realize it referred to the fact that the name cannot contain the term 'new'. For example:
```
Name 'new' is too vague. Use absolute time if needed e.g. 'summary_redesign_late_2015'
```
Updating the validation errors to be less ambiguous and provide clearer direction on why the name is not valid in a more human readable format.
/domain @Betterment/test_track_core @jmileham 
/no-platform
=> Make name validation errors be more informative

app/models/split.rb
Fixes rubocop related to line length. Also switches to used preferred `#add` syntax for errors.
/no-platform
=> Use #add when adding errors to error bag

Gemfile.lock
Updating database cleaner ahead of upgrading this app to rails 5.1. This is due to a deprecation warning that is accounted for in newer versions of database cleaner [here](https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/active_record/truncation.rb#L30).
/domain @betterzega @samandmoore 
/no-platform
=> update database cleaner to 1.7.0

Gemfile.lock
Upgrade Devise to version `4.4.3`
This is done to pave the way to Rails 5.3 which is supported by Devise 4.4.
Devise Changelog: https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#443---2018-03-17
Devise Diff from old version: https://github.com/plataformatec/devise/compare/v4.3.0...v4.4.3
/domain @samandmoore @betterzega 
/platform @samandmoore @betterzega
=> Upgrade Devise to 4.4.3

Gemfile.lock
Patch in response to CVE-2018-3760. We do not compile assets in production so the TestTrack app is not vulnerable by default, but best to put this vulnerable version of sprockets in the rearview anyway.
/domain @Betterment/test_track_core @samandmoore @aburgel
=> Upgrade to patched sprockets

Gemfile, Gemfile.lock, config/initializers/datadog.rb
This adds support for a DataDog integration. It configures the default process names as well so that they will come through as `test_track`, `test_track-http`, `test_track-active-record`, and `test_track-delayed_job`. 
Datadog will only be configured if the environment variable `DATADOG_ENABLED` is set to `true`.
/platform @jmileham @samandmoore
=> Adds ddtrace gem and configures DataDog

app/models/split_creation.rb, spec/models/split_creation_spec.rb
If you want to reenable a finished split via a migration, it won't actually un-finish it. This fixes that.
/no-platform
=> Clean out finished_at in create

app/controllers/concerns/cors_support.rb
We use Test Track on a few domains: example.org and sub.example.org. At example.org we have a link that redirects a user to sub.example.org. When the user lands onto sub.example.org and clicks back in Chrome Browser, it causes the CORS error at example.org, because the request to Test Track server has been cached with `Origin: sub.example.org`. I hope this link will explain what happens.
https://fetch.spec.whatwg.org/#cors-protocol-and-http-caches
=> set "Vary": "Origin" header

app/controllers/api/v1/split_registries_controller.rb, app/models/app_feature_completion.rb, app/models/assignment.rb, app/models/split.rb, app/models/split_registry.rb, spec/models/app_feature_completion_spec.rb, spec/models/assignment_spec.rb, spec/models/split_spec.rb
This knocks out the split registry to 100% false for a given split in response to feature incompleteness on the current client app build. In conjunction with #100, it means that folks who are using a version of a client that is not feature complete for a given gate will not see any explicit assignments for that gate (PR #100's doing), and instead will see weightings of 100% false (this PR's doing) that cause the client to disable the feature.
There will be a future PR to add "hard" assignments that will win over these knockouts. I expect the weightings to remain knocked out in that case, we'll just ship the hard assignments to the client to layer over top.
/platform @smudge @samandmoore
=> Knockout incomplete feature weightings

app/controllers/admin/bulk_assignments_controller.rb, app/controllers/api/v1/assignment_overrides_controller.rb, app/models/arbitrary_assignment_creation.rb, app/models/assignment.rb, app/models/bulk_assignment_creation.rb, app/models/bulk_reassignment.rb, app/views/admin/bulk_assignments/new.html.erb, db/migrate/20190408143237_add_force_to_assignments.rb, db/migrate/20190408144258_backfill_assignments.rb, db/migrate/20190408145933_add_not_null_constraints.rb, db/migrate/20190409164425_validate_not_null_constriants.rb, db/schema.rb, spec/controllers/api/v1/assignment_overrides_controller_spec.rb, spec/models/assignment_spec.rb, spec/models/bulk_assignment_creation_spec.rb, spec/models/bulk_reassignment_spec.rb
Adds a force flag to assignments which will later be plumbed into assignment hiding logic for app_feature_incompletions and app_remote_kills. Using this column for presentation comes later, and that's fine because no endpoints currently available will be impacted by the force flag.
The tests here are very high level, but actually give a lot of confidence. There were still-other tests that failed along the way and showed me where I was under-implementing this feature. I'm not sure the test strategy is super opinionated for all these models in general, but this testing strategy feels coherent with the way tests had been written before. What are your thoughts on that?
There's also a detail here that's kind of annoying - I want to add a not-null column to a potentially-very-large table …
=> Hard assignments

db/migrate/20190408144258_backfill_assignments.rb
Looks like the backfill causes latency jitter when saturating IOPS on our stage database. Adding sleeps to tone it down a little bit and see how that treats us.
/domain @alederman @bslakter
/no-platform
=> add sleeps to keep from slamming server, batch size 10k

app/controllers/api/v2/migrations/app_feature_completions_controller.rb, app/models/app.rb, app/models/app_feature_completion.rb, app/models/app_feature_completion_migration.rb, app/models/split.rb, app/types/app_version_type.rb, config/routes.rb, db/migrate/20190413110639_app_feature_completion_split_to_feature_gate.rb, db/schema.rb, spec/controllers/api/v2/migrations/app_feature_completions_controller_spec.rb, spec/factories/app_feature_completions.rb, spec/factories/splits.rb, spec/models/app_feature_completion_migration_spec.rb, spec/models/assignment_spec.rb, spec/models/split_spec.rb
This adds a new migration endpoint to create/update/destroy feature completions. I renamed a the AppFeatureCompletion.split_id column to feature_gate_id in the process and validated that it's the right kind of split now that I'm shoring this up for data integrity while receiving untrusted input.
I'll drop a comment with the version range that's real because this includes `remote_kill`'s commits right now.
=> Feature completion migration endpoint

app/controllers/api/v2/migrations/app_remote_kills_controller.rb, app/models/app.rb, app/models/app_remote_kill.rb, app/models/app_remote_kill_migration.rb, config/routes.rb, db/migrate/20190413210327_rekey_app_remote_kills.rb, db/schema.rb, doc/arch/adr-001.md, spec/controllers/api/v2/migrations/app_remote_kills_controller_spec.rb, spec/factories/app_remote_kills.rb, spec/models/app_remote_kill_migration_spec.rb, spec/models/app_remote_kill_spec.rb, spec/models/split_spec.rb
just like #108 only for remote_kills.
Will call out relevant diff below.
=> Remote kill migration endpoint

app/controllers/api/v2/migrations_controller.rb, app/models/app.rb, app/models/app_migration.rb, app/views/api/v2/migrations/index.jbuilder, config/routes.rb, db/migrate/20190413205758_create_app_migrations.rb, db/schema.rb, spec/controllers/api/v2/migrations_controller_spec.rb
This provides persistence/retrieval for migration versions so clients can know which migrations they still need to run, even when they merge out of order.
Will follow with relevant commits.
=> App migrations

app/controllers/api/v1/app_identifier_visitor_configs_controller.rb, app/controllers/api/v1/app_visitor_configs_controller.rb, app/models/app.rb, app/models/app_version_build_path.rb, app/models/visitor.rb, app/views/api/v1/app_identifier_visitor_configs/show.json.jbuilder, app/views/api/v1/app_visitor_configs/_show.json.jbuilder, app/views/api/v1/app_visitor_configs/show.json.jbuilder, config/routes.rb, spec/controllers/api/v1/app_identifier_visitor_configs_controller_spec.rb, spec/controllers/api/v1/app_visitor_configs_controller_spec.rb, spec/models/app_version_build_path_spec.rb
Provides endpoints for clients in the field to filter assignments and do contextual variant knockouts.
I believe this will be the last TT PR before MVP of mobile extensions is done server side.
Per usual there's a bunch of commits in here that are not relevant due to stacked PRs. I'll call out the real diff below.
/domain @JonLz for mobile integration needs - this would be what you'd be implementing to client side.
=> Mobile client endpoints

app/controllers/api/v2/migrations/split_decisions_controller.rb, app/models/split_decision_migration.rb, config/routes.rb, spec/controllers/api/v2/migrations/split_decisions_controller_spec.rb, spec/models/split_decision_migration_spec.rb
Adds a new migration endpoint for deciding splits from the new migration CLI. It's very similar to retirement except it actually unretires a split that has been retired. This expressive capability to be able to unretire a split back to a decided state is why it makes sense to even make this a migration, otherwise, it would be impossible to revert a retirement of a decided split without temporarily pivoting through active and clicking a button in the admin console.
=> Add split decisions controller

app/models/assignment.rb, app/models/split.rb, app/models/visitor_supersession.rb, spec/models/visitor_supersession_spec.rb
Don't copy feature_gate assignments on visitor supersession to make it impossible to piggyback on privileged identities to get into closed features.
Also added a test to codify the behavior that assignments to decided splits should either not be copied or their updated_at be backdated so as to hide the assignment. The current implementation doesn't copy them, and that is fine. There's a story for copying them and backdating updated_at, but I don't think it's that important. It would only be interesting if a split were undecided and we wanted the assignment to come back to life for the superseding identity, but that feels unnecessary. Either way the current test will work if that behavior is changed.
/domain @Betterment/test_track_core @samandmoore 
=> Don't merge feature gate assignments when superseding visitors

.travis.yml, Gemfile, Gemfile.lock, config/initializers/airbrake.rb, config/initializers/sentry.rb
Adds sentry support and makes Airbrake support optional (not requiring the gem if not needed).
/platform @samandmoore @aburgel
=> Add sentry support, make airbrake optional

.gitignore, app/models/arbitrary_assignment_creation.rb, spec/models/arbitrary_assignment_creation_spec.rb, spec/spec_helper.rb
/no-platform
This addresses a UX bug in the chrome extension.
For a decided, but still active, split where a previous assignment existed, using the chrome extension to assign the same variant effectively no-ops, which looks like nothing happens within the chrome extension. This makes it appear as if test track is broken.
How we get here is a little convoluted, but here are the important points:
1. Assigning to the same variant results in no change in the assignments table, including no change to the `updated_at` attribute.
2. For a decided split, assignments that were updated before the split's `decided_at` will not appear in the assignment registry.
3. Within the chrome extension, a split appears unassigned if there is no record in the assignment …
=> Touch assignments to ensure chrome extension sees changes

app/models/deterministic_assignment_creation.rb, spec/controllers/api/v1/assignment_events_controller_spec.rb, spec/models/deterministic_assignment_creation_spec.rb
#119 introduced a change that unintentionally caused the `assignment_event` endpoint to touch updated_at on existing assignments for decided splits when clients, seeing no assignment (due to assignment masking in the relatively-new decision logic) attempted to create fresh assignments. As a result, the old assignment would win over the decision, effectively negating the decision.
This only impacts experiments, as feature gates are already immune to being explicitly assigned via the `assignment_event` endpoint
I got to this implementation by testing from the outside in and redefining a test whose title matched what I wanted to be more strict. Ultimately it turns out that the `DeterministicAssignmentCreation` model was way fancier than it needed to be, unless I'm missing something. …
=> Bugfix: Noop assignment_events for existing assignments

app/models/split.rb, app/views/admin/splits/_details.html.erb, spec/models/split_spec.rb
fixes #122
There are no tests on this field, and I didn't add any, but the Active codepath actually covers the finished and decided conditionals via fallthru, so this would be hard to break unless the definitions of finished or decided changed.
=> Show decided state in admin

app/models/arbitrary_assignment_creation.rb, app/models/deterministic_assignment_creation.rb, spec/controllers/api/v1/assignment_events_controller_spec.rb, spec/models/arbitrary_assignment_creation_spec.rb, spec/models/deterministic_assignment_creation_spec.rb
NOTE: This is built upon #125. I had to open a new PR since that PR was off of a fork. I made the following modification: Consolidated the logic in `DeterministicAssignmentCreation` to reduce coupling to `ArbitraryAssignmentCreation` and to close the window in which a new variant could  be unintentially assigned.
https://github.com/Betterment/test_track/pull/123 introduced a change that results in the `mixpanel_result` never being updated when the client sends a request to `DeterministicAssignmentCreation` for an existing assignment. I believe the sequence of events would look something like this:
1. The client encounters a split and sends the first request to `Api::V1::AssignmentEventsController` with params that have a `nil` `mixpanel_result`.
2. The client's request to the analytics …
=> Update assignment when mixpanel result has changed

app/controllers/api/v4/app_identifier_visitor_configs_controller.rb, app/controllers/api/v4/app_visitor_configs_controller.rb, app/controllers/api/v4/split_registries_controller.rb, app/models/split_registry.rb, app/views/api/v4/app_identifier_visitor_configs/show.json.jbuilder, app/views/api/v4/app_visitor_configs/_show.json.jbuilder, app/views/api/v4/app_visitor_configs/show.json.jbuilder, app/views/api/v4/split_registries/show.json.jbuilder, config/application.rb, config/routes.rb, spec/controllers/api/v2/split_registries_controller_spec.rb, spec/controllers/api/v3/split_registries_controller_spec.rb, spec/controllers/api/v4/app_identifier_visitor_configs_controller_spec.rb, spec/controllers/api/v4/app_visitor_configs_controller_spec.rb, spec/controllers/api/v4/split_registries_controller_spec.rb, spec/models/split_registry_spec.rb
in #148 we discussed creating a v4 version of the /builds/:timestamp/split_registry endpoint that is used by the rails client and js client (transitively).
this PR adds that endpoint for future consumption. this is nice in that it allows all the clients to be consuming the same version of the split registry schema (v4) whenever they're updated.
this PR also introduces the `experience_sampling_weight` to the v4 endpoints.
**NOTE: i moved the `experience_sampling_weight` loading behavior from the `SplitRegistry` model to the `Rails.configuration` in `application.rb`. This felt like a better way to share the behavior between the `SplitRegistry`-based and the non-`SplitRegistry`-based  ways of getting at the list of applicable splits for a client (via app+version+timestamp or via build …
=> More v4 endpoint additions

README.md
Links out to the newly-published dart TT client
/domain @Betterment/test_track_core @samandmoore @btrautmann 
/no-platform
=> chore: Add reference to dart TT client

Gemfile, Gemfile.lock
This gem was out-of-date for a long time, and got inadvertently upgraded in #182. The newer version attempts to connect without valid credentials, so we're removing it for now (to avoid solving for the ability to optionally inject valid credentials).
/no-platform
=> Remove the newrelic RPM gem

app/controllers/api/v2/migrations/splits_controller.rb, app/models/split_upsert.rb, spec/controllers/api/v2/migrations/splits_controller_spec.rb
Supports updating ownership of a split from testtrack-cli 1.5.0.
=> Support updating owner via migration

config/application.rb
`parent_name` is deprecated in Rails 6.1, so this PR changes a stray call into `module_parent_name`
=> Fix `parent_name` deprecation

Gemfile, Gemfile.lock, app/views/api/v1/visitor_details/_assignment_detail.json.jbuilder, config/initializers/types.rb
This updates `test_track` to Rails 7 and fixes a breaking deprecation and a lint.
I'll comment on interesting stuff inline
/domain
=> Upgrade to Rails 7

.github/workflows/ci.yml, Gemfile, Gemfile.lock, README.md, spec/rails_helper.rb, spec/system/admin_split_decision_create_spec.rb, vendor/gems/ruby_spec_helpers/lib/ruby_spec_helpers/capybara_configuration.rb, vendor/gems/ruby_spec_helpers/ruby_spec_helpers.gemspec
- Replace selenium-webdriver with cuprite.
- Upgrade [primer_view_components](https://github.com/primer/view_components) up to a version that fixes JS errors detected in system tests.
- Remove chromedriver from ci.yml (no needed anymore!).
/task https://app.asana.com/0/1205654148374805/1205654148376945/f
=> Migrate capybara driver to cuprite

app/assets/stylesheets/application.sass.scss, app/assets/stylesheets/components/_banner.scss, app/helpers/application_layout_helper.rb, app/views/layouts/application.html.erb, spec/helpers/application_layout_helper_spec.rb, spec/requests/admin/split_details_spec.rb
Currently, if an organization uses Test Track for multiple environments (e.g. production and stage), it can be a bit difficult to discern at first glance for which environment a user is managing a given split test.
This proposed change gives users the option to set a `DEPLOYMENT_ENV_LABEL` variable in the `.env` or `.env.local` file, which will subsequently be rendered in a bright red banner, like so:
The banner is intentionally a tad obnoxious to make it glaringly obvious to the user which environment they are in. 
When no `DEPLOYMENT_ENV_LABEL` variable is set, the header renders as usual:
I envision organizations using the existing state for production and the banner state for a non-production environment (or perhaps vice-versa). 
=> Add Optional Environment Banner

.github/workflows/ci.yml
This is blocking the omniauth-saml security patch (https://github.com/Betterment/test_track/pull/223; see action run: https://github.com/Betterment/test_track/actions/runs/10819720832/job/30018225320?pr=223). We're on Rails 7, so we don't need to worry about https://github.com/Betterment/test_track/pull/187/files#r1150893892
I'm skipping bumping `rubocop.yml`'s `TargetRubyVersion` in the interest of time.
> Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
> If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or …
=> drop 3.0 from GH matrix

bin/webpack
see: https://github.com/Betterment/test-track-app/pull/31#discussion_r1757654499
In CI we have a frontend build verification step which runs either `bin/vite` or `bin/webpack`, but `test_track` uses none of those. As a workaround, this commit adds a `bin/webpack` script that just runs `yarn build:css` internally.
> If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
> Thanks for contributing to TestTrack!
=> add a `bin/webpack`

package.json, pnpm-lock.yaml
The primer versions added in #254 caused a visual regression.
/no-platform
=> Revert primer upgrade

Gemfile, Gemfile.lock, bin/setup, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/stage.rb, config/environments/test.rb, config/initializers/content_security_policy.rb, config/initializers/filter_parameter_logging.rb, config/initializers/permissions_policy.rb
> Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
I ran `bundle exec rake app:update` and picked changes I thought were sensible (so, benign changes like quoting/prose changes, or new defaults added by the 7.1 templates)
I'm also updating `load_defaults` to 7.1 (since this doesn't depend on our internal runtime configuration). We tested this on our stage instance.
> If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
I had to bump `primer_view_components` to 0.14.0, since that's the first …
=> feat: Run `rake app:update` and opt into Rails 7.1 defaults
