Betterment/test_track

- Gemfile
- Gemfile.lock
/domain @samandmoore @aburgel @rynonl
> Upgrade deps

- README.md
/domain @samandmoore @rynonl @aburgel 
Let github visitors join the slack team and get help or join the conversation about TestTrack development.
h/t @ceslami
> Add slackin badge

- app/controllers/admin/splits_controller.rb
/domain @samandmoore @rynonl @jmileham
> sort splits on index page by name

- Gemfile
- Gemfile.lock
- Procfile
- bin/delayed_job
- config/puma.rb
- db/migrate/20161220150705_create_delayed_jobs.rb
- db/schema.rb
/domain @rynonl @jmileham 
/cc @reustmd @dschaub @while1malloc0 
This changeset includes support for delayed job. It's not being utilized yet, but I thought it would be a good idea to land this as it's own PR to keep things small.
I'm open to expanding on this PR to include a feature that uses DJ.
> Add support for DelayedJob

- config/environments/demo.rb
- config/secrets.yml
> Adding demo environment to test track application

- app/models/admin.rb
- spec/controllers/api/v1/visitors_controller_spec.rb
- spec/models/admin_spec.rb
> Fix case sensitivity bug in SAML auth

- app/controllers/admin/bulk_assignments_controller.rb
- app/jobs/bulk_assignment_job.rb
- app/models/bulk_assignment_creation.rb
- spec/features/admin_bulk_assignment_create_spec.rb
- spec/models/bulk_assignment_creation_spec.rb
/domain @samandmoore @while1malloc0 @agirlnamedsophia
> Delay mass assignments

- Gemfile.lock
- lib/tasks/vendor_deps.rake
- vendor/gems/style-closet/app/assets/stylesheets/_style-closet-core.scss
- vendor/gems/style-closet/app/assets/stylesheets/_style-closet.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_forms.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_icons.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_images.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_layout.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_layouts.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_tables.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/_takeover-footer.scss
- vendor/gems/style-closet/app/assets/stylesheets/style-closet/abstracts/_color-rule.scss
- vendor/gems/style-closet/lib/style_closet/version.rb
* This updates test track's style closet so we can implement `layout` styles.
> Updates stylecloset

- app/views/admin/bulk_assignments/new.html.erb
- app/views/admin/decisions/new.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/admin/split_configs/new.html.erb
- app/views/admin/splits/_split.html.erb
- app/views/admin/splits/_split_registry.html.erb
- app/views/admin/splits/_table_header.html.erb
- app/views/admin/splits/index.html.erb
- app/views/admin/splits/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
* This adjusts indentation across the board for consistency
> Adjusting indentation to be consistent

- app/assets/stylesheets/components/_inputs.scss
- app/assets/stylesheets/typography/_base.scss
- app/assets/stylesheets/typography/_utilities.scss
- app/helpers/application_layout_helper.rb
- app/views/admin/bulk_assignments/new.html.erb
- app/views/admin/decisions/new.html.erb
- app/views/admin/split_configs/new.html.erb
- app/views/admin/split_details/edit.html.erb
- app/views/admin/splits/_split.html.erb
- app/views/admin/splits/_variants.html.erb
- app/views/admin/splits/index.html.erb
- app/views/admin/variant_details/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flash.html.erb
- app/views/shared/_form_footer.html.erb
- spec/helpers/application_layout_helper_spec.rb
- spec/support/pages/admin/split_config_new_page.rb
- spec/support/pages/admin/split_show_page.rb
* final tweaks per design QA (last style update I promise)
> Final design Adjustments

- app/controllers/admins/omniauth_callbacks_controller.rb
/domain @jmileham 
/platform @jmileham
> Attempt to un-break admin interface

- db/schema.rb
I never ran `rake db:migrate` when testing on Rails 5, so I didn't notice that this file would change.
So here are the changes!
/domain @Betterment/test_track_core @jmileham @samandmoore 
/no-platform
> Changes to schema file after Rails 4->5 upgrade

- app/models/deterministic_assignment_creation.rb
Was reviewing the code and happened to notice that this delegation is being overridden by real methods _and_ would not work if it wasn't being overridden. 
/no-platform
> delete invalid and unused delegation

- app/controllers/admin/split_configs_controller.rb
- app/controllers/api/v1/split_configs_controller.rb
- app/models/split.rb
- app/models/split_upsert.rb
- spec/models/split_spec.rb
- spec/models/split_upsert_spec.rb
This is a reopen of already-reviewed https://github.com/jmileham/test_track/pull/2 against Betterment master.
Please re LG! Thanks!
/domain @smudge 
/platform @smudge 
/cc @samandmoore
> SplitCreation -> SplitUpsert

- app/models/assignment.rb
- app/models/split.rb
- spec/models/assignment_spec.rb
- spec/models/split_spec.rb
~~Submitting this PR before previous merges. Much less controversial, but the body of it is only [the latest commit](https://github.com/Betterment/test_track/pull/105/commits/a8eef2280699120b650e67dcc603738035f14851) - the rest is a duplicate of #104.~~
> Force beats feature incomplete

- app/models/app_feature_completion.rb
- app/models/app_remote_kill.rb
- app/models/assignment.rb
- app/models/split.rb
- db/migrate/20190409231451_create_app_remote_kills.rb
- db/schema.rb
- spec/factories/app_remote_kills.rb
- spec/models/app_feature_completion_spec.rb
- spec/models/app_remote_kill_spec.rb
- spec/models/assignment_spec.rb
- spec/models/split_spec.rb
Adds app_remote_kill functionality. Will annotate below.
> Remote kill

- app/models/app_remote_kill.rb
- app/models/assignment.rb
- app/models/split.rb
- doc/arch/adr-001.md
- doc/arch/adr-002.md
- spec/models/app_remote_kill_spec.rb
- spec/models/assignment_spec.rb
- spec/models/split_spec.rb
This is a behavior change relative to #106 described here: https://github.com/Betterment/test_track/pull/106#discussion_r275734607
Actual diff to follow...
> Remote kills are absolute

- doc/arch/adr-002.md
No change in the ADR, just a more informed consequences readout now that TT CLI is a thing.
/no-platform
> clarify consequences of remote kill absolute ADR

- app/controllers/api/v4/app_identifiers_controller.rb
fix lint violation merged in previous PR
/no-platform
i missed this when i ran the build locally (travis us hanging up for me)
> fix linter warning :facepalm:

- app/models/split_detail.rb
- app/views/admin/split_details/edit.html.erb
- spec/support/pages/admin/split_show_page.rb
- spec/system/admin_split_details_create_spec.rb
Allows individual fields to be populated on the split details page.
> Change Field Requirements on Split Detail Page

- Gemfile.lock
> Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
Nothing faaancy. Just updating some deps.
/no-platform
> use latest nokogiri and rack to address dependabot issues

- .github/workflows/ci.yml
- Gemfile.lock
https://github.com/Betterment/test_track/security/dependabot/55
> Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
upgrade puma to address security alert
/no-platform
> upgrade puma to address security alert

- Rakefile
> fix test runs

- package.json
- pnpm-lock.yaml
> Fix failure on with @primer dependencies on build:css
